name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: "Pre Release"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: "Build"
      run: make linux
    - name: "Create Release"
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "v0.0.1"
        title: Release ${{ github.ref }}
        body: |
          first release
        files: |
          ./bin/*
          ./README.md
          ./src/*